backend:
  name: git-gateway
  branch: master
media_folder: static/assets
public_folder: assets
collections:
  - name: pages
    label: Pages
    files:
      - name: faq
        label: "Frequently Asked Questions"
        file: content/frequently-asked-questions.md
        fields:
          - { label: Title, name: title, widget: string }
          - name: qanda
            label: "Q and A"
            widget: list
            fields:
              - { label: Question, name: question, widget: string }
              - { label: Answer, name: answer, widget: string }
      - name: privacy-policy
        label: "Privacy Policy"
        file: content/privacy-policy.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
      - name: terms-and-conditions
        label: "Terms and Conditions"
        file: content/terms-and-conditions.md
        fields:
          - { label: Title, name: title, widget: string }
          - name: conditions
            label: "Conditions"
            widget: list
            fields:
              - { label: Condition Title, name: subtitle, widget: string }
              - { label: condition, name: condition, widget: markdown }
